### ISSUE TITLE
Use proper API 

### ISSUE THREAD

**Issue by vBm** [wows-stats/wows-stats#1]
Using proper API provided by WG would be much faster and easier.

https://eu.wargaming.net/developers/

**Comment by tianweiliu** [comment]
Thanks for letting me know! I didn't even know that exists! Looks like they haven't open up developer portal to NA. I will take a look at the EU version.

**Comment by tianweiliu** [comment]
Just did some experiments. Looks like .com (NA) api is available just like the .eu (EU) version. I will start working on that.

**Comment by tianweiliu** [comment]
I missed the region selection drop down menu yesterday. NA has developer console as well. I am starting to implement all the functionalities.
