### ISSUE TITLE
hide_profile = true > brings script to a crash

### ISSUE THREAD

**Issue by wofnull** [wows-stats/wows-stats#13]
If in the Stats Reply the Variable

data.hidden_profile 
is set to true, the profile contains no stats at all, furthermore the variables, pulled from the script are not present.

This leads to a crash of the script.

An Example of this is the ( EU ) Player -> Andy_Nichols http://worldofwarships.eu/de/community/accounts/search/?search=Andy_Nichols

Please take a look and fix this :)

**Comment by wofnull** [comment]
If you change in index.js on line 53 from:
                                    if (stats.status == "ok") {
to:
                                    if (stats.status == "ok" && stats.meta.hidden == null) {
the field gets checked by the script and gets skipped from the ship fetch, stopping the script to crash.

Problem is not solved completly, but its a dirty quickfix, aborting the crashing of the script.

**Comment by tianweiliu** [comment]
@wofnull Sorry about the long wait for the fix! I have implemented the support for private profile which will display "Private" under player's name instead of crashing the app :smile:.
