### ISSUE TITLE
lol

### ISSUE THREAD

**Issue by SanaWarship** [wows-stats/wows-stats#14]
XVM n'apporte pas d'environnement toxique ?

hahahahaaha....please. Si tu refiles un outil à une brêle non qualifié, il se coupera la main avec.

XVM n'est pas le fond du problème, c'est l'utilisation que la plupart en font. Denigrer, se la peter et jouer les gros dure sur les forums, et pire, IG !

Donc s'il te plait, XVM n'est pas la cause première, mais la source de la mauvaise ambiance sur WOT par exemple. Je ne te remercie pas d'avoir pondu ton travail pour warship. Désormais, on va avoir X Jean Kevin qui vont venir nous faire chier sur le chat IG. Bon, comme mauvais joueur, tout le monde en sera la victime.

**Comment by wofnull** [comment]
First things first, try to express yourself and your anger about this in a language that anyone understands.

Second: This is no bug Report, this is a rant about how worried you are about that XVM destroys the game for you.

Firstly, blame Wargaming, not this programmer, Wargaming gives out the API & Access to it, so therefore this is their fault.
Secondly, nobody is harmed from this tool, everyone can use it or not use it. It makes others not better / worser and it makes yourself aswell not better or worser. It is intended for Information about the stats from other players and not more.

**Comment by tianweiliu** [comment]
@wofnull Thanks for your response. I think the recent added private profile feature is a nice move from Wargaming because instead of blocking everything all together they gave the choice to players.

**Comment by tianweiliu** [comment]
@SanaWarship I understand your concern, but apperantly you did not even read my message before creating this ticket.

```
You agree that statistics of a player does NOT mean how a player will perform in a game, and you will NOT use this tool in any way to create a toxic environment or demonstrate any unethical/immortal behaviour in World of Warships. If you do NOT agree, you shall NOT use this app.
```

Anyway, make your profile private and enjoy the game.

**Comment by SanaWarship** [comment]
Hahaha. idiot. 

----- Mail original -----

De: "Tianwei Liu" notifications@github.com 
À: "wows-stats/wows-stats" wows-stats@noreply.github.com 
Cc: "SanaWarship" fastarea.marcel@laposte.net 
Envoyé: Mercredi 27 Janvier 2016 08:31:36 
Objet: Re: [wows-stats] lol (#14) 

@SanaWarship I understand your concern, but apperantly you did not even read my message before creating this ticket. 
You agree that statistics of a player does NOT mean how a player will perform in a game, and you will NOT use this tool in any way to create a toxic environment or demonstrate any unethical/immortal behaviour in World of Warships. If you do NOT agree, you shall NOT use this app. 

Anyway, make your profile private and enjoy the game.

**Comment by tianweiliu** [comment]
@SanaWarship Thank you for taking your time creating a GitHub account just to troll this project. You made my day, sir.
