### ISSUE TITLE
Expand parser to other servers as well

### ISSUE THREAD

**Issue by vBm** [wows-stats/wows-stats#2]
Currently only NA (.com) is hardcoded, would be nice to see wows-stats work with other clusters as well.

**Comment by tianweiliu** [comment]
I will add an environment variable to support other servers. Would you mind sending me some player names so i can do some tests?

**Comment by tianweiliu** [comment]
Both `master` which uses the web crawler and `wg-api` which uses Wargaming's API support multiple regions now. I haven't be able to test them because I don't have an EU account for World of Warships.
